---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: mcfitz2
name: proxmox_backup
version: "0.0.1"
readme: README.md
authors:
  - Micah Fitzgerald (github.com/mcfitz2)
description: Collection for backing up and restoring Proxmox resources
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - proxmox
  - backup
repository: https://github.com/mcfitz2/ansible-collection-proxmox_backup
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/mcfitz2/ansible-collection-proxmox_backup
issues: https://github.com/mcfitz2/ansible-collection-proxmox_backup/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
