---
name: Release and Deploy collection
on: # yamllint disable-line rule:truthy
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      ANSIBLE_GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
    steps:

      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Get current version
        id: cversion
        run: echo "::set-output name=version::$(grep version galaxy.yml | awk -F'"' '{ print $2 }')"

      - name: Publish collection
        run: ansible-playbook -i 'localhost,' ci/deploy.yml -e "tag=${{ steps.cversion.outputs.version }}"