on:
  push:
    tags:
    - '*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      ANSIBLE_GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Publish collection
        run: ansible-playbook -i 'localhost,' ci/deploy.yml -e "tag=${{ github.ref_name }}"
      - name: Add galaxy.yml
        run: git add galaxy.yml
      - name: Commit galaxy.yml change
        run: git commit -m "Updated galaxy version to ${{ github.ref_name }}"
      - name: Push to main
        run: git push origin main