on:
  push:
    tags:
    - '*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      ANSIBLE_GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Publish collection
        run: ansible-playbook -i 'localhost,' ci/deploy.yml -e "tag=${{ github.ref_name }}"
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'galaxy.yml'
          default_author: github_actor
          fetch: false
          message: 'Updating galaxy.yml version to ${{ github.ref_name }}'
          push: true